# Based on https://github.com/middleman/middleman/issues/2289
name: Run script and deploy to GitHub Pages

# 3 7,11,14,21 *   *   *

on:
  push:
    branches: ["main"]
  workflow_dispatch:
  schedule:
    - cron: "3 7,11,14,21 * * *"
    - cron: "33 16 * * *"

jobs:
  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    permissions:
      pages: write      # to deploy to Pages
      id-token: write
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup Pages
        uses: actions/configure-pages@v3
      # ----------------------------------------------------Ruby
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: .tool-versions
          bundler-cache: true
      - name: Ruby version
        run: |
          ruby -v
      - name: Setup Ruby dependencies
        run: |
          gem update bundler
          bundle config set without 'development'
          bundle install --jobs 4 --retry 3
      # ----------------------------------------------------Chrome
      - uses: browser-actions/setup-chrome@v1
      - name: Chrome version
        run: chrome --version
      - name: Install ansifilter
        run: |
          curl -O http://www.andre-simon.de/zip/ansifilter-2.19.tar.bz2
          tar xjf ansifilter-2.19.tar.bz2
          cd ansifilter-2.19
          make help
          make
          sudo make install
          make clean
          cd
      - uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "America/New_York"
          timezoneMacos: "America/New_York"
      - name: Run script and export HTML file
        run: |
          mkdir ./output
          bundle exec ruby netnutrition-helper.rb North | ansifilter --html -o ./output/index.html
      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: './output'
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2
